// Данные достижений Stay Out, взяты со страницы so-wiki.ru/wiki/Достижения.
// Источник огромный (304 записи) и отдаёт данные только частями — этот файл
// это первая порция (~114 шт). Формат специально плоский и однотипный,
// чтобы можно было быстро дописать остальные достижения тем же способом:
// { name, description, category, hidden, exp }

export const ACHIEVEMENTS = [
  { name: '"Бульдозер"', description: 'Успешно пройти событие "Бульдозер" и получить награду', category: 'События', hidden: false, exp: 2000 },
  { name: '"Другая жизнь Ивана"', description: 'Собрать всю историю "Другая жизнь Ивана"', category: 'Истории', hidden: true, exp: 500000 },
  { name: '"Забытый чемодан"', description: 'Успешно пройти событие "Забытый чемодан" и получить награду', category: 'События', hidden: false, exp: 2000 },
  { name: '"Обелиск"', description: 'Успешно пройти событие "Обелиск" и получить награду', category: 'События', hidden: false, exp: 2000 },
  { name: '"Противогаз и розы"', description: 'Собрать весь сборник стихов "Противогаз и розы"', category: 'Истории', hidden: true, exp: 600000 },
  { name: '"Разбитый колокол"', description: 'Успешно пройти событие "Разбитый колокол" и получить награду', category: 'События', hidden: false, exp: 2000 },
  { name: '"Старый телевизор"', description: 'Успешно пройти событие "Старый телевизор" и получить награду', category: 'События', hidden: false, exp: 2000 },
  { name: '"Юность"', description: 'Собрать всю коллекцию журналов "Юность"', category: 'Истории', hidden: true, exp: 150000 },
  { name: 'Адская кухня', description: 'Убить 100 пряничных человечков во время Пряничного безумия.', category: 'События', hidden: true, exp: 500 },
  { name: 'Аномальная коллекция', description: 'Собрать все виды и типы артефактов с помощью МЗА из аномалий.', category: 'Артефакты', hidden: true, exp: 100000 },
  { name: 'Артефактовый король', description: 'Извлечь из аномалий 1000 артефактов любого типа', category: 'Артефакты', hidden: true, exp: 30000 },
  { name: 'Аэропорт Конуково', description: 'Добро пожаловать на локацию "Аэропорт"', category: 'Исследование', hidden: true, exp: 2000 },
  { name: 'Банчила', description: 'Продать на доске объявлений 1000 предметов', category: 'Торговля', hidden: true, exp: 40000 },
  { name: 'Барыга', description: 'Продать НИПу предметов на сумму 1000000 рублей', category: 'Торговля', hidden: true, exp: 1000 },
  { name: 'Бинтарь, в душе', description: 'Совершить 1000 попыток создать бинты', category: 'Создание предметов', hidden: true, exp: 1000 },
  { name: 'Биохимик', description: 'Совершить 1000 попыток создать пробирки с кровью и ядом мутантов', category: 'Создание предметов', hidden: true, exp: 40000 },
  { name: 'Боевой медик', description: 'Поднять на ноги другого игрока лежащего без сознания 1000 раз', category: 'Лечение', hidden: true, exp: 30000 },
  { name: 'Бунтарь', description: 'Стрелять перед охраной и улететь из безопаски', category: 'Нарушения', hidden: true, exp: 0 },
  { name: 'Быть ПК - нехорошо', description: 'Получить ПК-статус', category: 'Нарушения', hidden: true, exp: 500 },
  { name: 'В законе', description: 'Побывать в Тюрьме 1000 раз. Похоже, тюрьма вам ближе реального мира', category: 'Исследование', hidden: true, exp: 40000 },
  { name: 'В подъездах опасно', description: 'Быть застреленным в подъезде на Окрестностях Любеча', category: 'Убийство сталкеров', hidden: true, exp: 0 },
  { name: 'В списке форбс', description: 'Накопить 100000000 рублей', category: 'Торговля', hidden: true, exp: 100000 },
  { name: 'Вандал', description: 'Разобрать 100 предметов', category: 'Исследование', hidden: true, exp: 1000 },
  { name: 'Везувий', description: 'Добро пожаловать на локацию "Везувий"', category: 'Исследование', hidden: true, exp: 2000 },
  { name: 'Ветеринар', description: 'Совершить 100 попыток создать пробирки с кровью и ядом мутантов', category: 'Создание предметов', hidden: false, exp: 4000 },
  { name: 'Вечно второй', description: 'Занять 2 место в любом ивенте 10 раз', category: 'События', hidden: true, exp: 500 },
  { name: 'Внимательный', description: 'Найти спрятанный схрон', category: 'Исследование', hidden: false, exp: 200 },
  { name: 'Воин', description: 'Убить 1000 игроков во время захватов', category: 'Захваты', hidden: true, exp: 50000 },
  { name: 'Вот ты какой 6Б13', description: 'Обменять Метеор на 6Б13', category: 'Торговля', hidden: true, exp: 10000 },
  { name: 'Врач', description: 'Полечить других игроков 1000 раз', category: 'Лечение', hidden: true, exp: 30000 },
  { name: 'Все получится', description: 'Неудача при создании любого предмета', category: 'Создание предметов', hidden: true, exp: 200 },
  { name: 'Всегда первый', description: 'Занять первое место в любом ивенте', category: 'События', hidden: true, exp: 1000 },
  { name: 'Выживший с Радиостанции', description: 'Собрать все записки выжившего с Радиостанции', category: 'Истории', hidden: true, exp: 10000 },
  { name: 'Глубина', description: 'Самая глубокая точка в мире', category: 'Исследование', hidden: false, exp: 5000 },
  { name: 'Голод не тетка', description: 'Съесть сырое мясо', category: 'Выживание', hidden: true, exp: 300 },
  { name: 'Гроза бесов', description: 'Убить 10000 бесов', category: 'Убийство противников', hidden: true, exp: 30000 },
  { name: 'Гроза бляков', description: 'Убить 10000 бляков', category: 'Убийство противников', hidden: true, exp: 30000 },
  { name: 'Гроза бруторов', description: 'Убить 10000 бруторов', category: 'Убийство противников', hidden: true, exp: 20000 },
  { name: 'Гроза ведунов', description: 'Убить 10000 ведунов', category: 'Убийство противников', hidden: true, exp: 40000 },
  { name: 'Гроза верлиок', description: 'Убить 10000 верлиок', category: 'Убийство противников', hidden: true, exp: 30000 },
  { name: 'Гроза домовых', description: 'Убить 10000 домовых или леших', category: 'Убийство противников', hidden: true, exp: 20000 },
  { name: 'Гроза драугов', description: 'Убить 10000 драугов', category: 'Убийство противников', hidden: true, exp: 100000 },
  { name: 'Гроза кабанов', description: 'Убить 10000 кабанов', category: 'Убийство противников', hidden: true, exp: 20000 },
  { name: 'Гроза крыс', description: 'Убить 10000 крыс', category: 'Убийство противников', hidden: true, exp: 10000 },
  { name: 'Гроза медведей', description: 'Убить 10000 медведей', category: 'Убийство противников', hidden: true, exp: 60000 },
  { name: 'Гроза отверженных', description: 'Убить 10000 отверженных', category: 'Убийство противников', hidden: true, exp: 20000 },
  { name: 'Гроза пауков', description: 'Убить 10000 пауков', category: 'Убийство противников', hidden: true, exp: 30000 },
  { name: 'Гроза репьев', description: 'Убить 10000 репьев', category: 'Убийство противников', hidden: true, exp: 50000 },
  { name: 'Гроза собак', description: 'Убить 10000 собак', category: 'Убийство противников', hidden: true, exp: 20000 },
  { name: 'Гроза студней', description: 'Убить 10000 студней', category: 'Убийство противников', hidden: true, exp: 30000 },
  { name: 'Гурман', description: 'Посетить локацию Гурман', category: 'Исследование', hidden: true, exp: 200 },
  { name: 'Да будет свет', description: 'Зажечь спички', category: 'Выживание', hidden: true, exp: 100 },
  { name: 'Да сколько можно', description: 'Быть застреленным игроком 200 раз', category: 'Убийство сталкеров', hidden: true, exp: 2000 },
  { name: 'Делец', description: 'Продать НИПу предметов на сумму 100000 рублей', category: 'Торговля', hidden: true, exp: 100 },
  { name: 'Дипломатия', description: 'Заключить союз с другой группировкой', category: 'Группировка', hidden: false, exp: 500 },
  { name: 'Домашняя работа', description: 'Собрать все материалы по истории о беженцах одного школьного класса', category: 'Истории', hidden: true, exp: 40000 },
  { name: 'Дробилка мне не ровня!', description: 'Продержаться минуту в дробилке и не умереть', category: 'Выживание', hidden: true, exp: 2000 },
  { name: 'За что', description: 'Быть застреленным игроком', category: 'Убийство сталкеров', hidden: true, exp: 0 },
  { name: 'Зажигательный бармен', description: 'Совершить 1000 попыток создать Коктейль Молотова', category: 'Создание предметов', hidden: true, exp: 20000 },
  { name: 'Закупщик', description: 'Купить на доске 100 предметов', category: 'Торговля', hidden: true, exp: 4000 },
  { name: 'Записки потерянного сталкера', description: 'Собрать все записки потерянного сталкера', category: 'Истории', hidden: true, exp: 5000 },
  { name: 'Зато в цирке не выступаю!', description: 'Забраться на Золотой Шар в городе N в форме медведя, и встать на задние лапы.', category: 'Исследование', hidden: true, exp: 500 },
  { name: 'Заядлый Убийца Зловещего Паукана', description: 'Убить Зловещего Паукана 100 раз', category: 'События', hidden: true, exp: 500000 },
  { name: 'Золотые руки', description: 'Починить экипировку с помощью набора для подшива одежды', category: 'Ремонт', hidden: false, exp: 3000 },
  { name: 'Зона забрала', description: 'Умереть от аномалии', category: 'Смерть', hidden: true, exp: 0 },
  { name: 'И шлем не помеха', description: 'Попасть (или убить) выстрелом в голову через шлем с расстояния 200 метров', category: 'Убийство сталкеров', hidden: true, exp: 50000 },
  { name: 'И это ты называешь удар', description: 'Во время события Куча Мала и Мутантов Шабаш, находясь в форме крысы, убить другого игрока, который находится в форме человека.', category: 'События', hidden: true, exp: 500 },
  { name: 'Игра - это моя жизнь', description: 'Провести в игре 5000 часов', category: 'Исследование', hidden: true, exp: 5000000 },
  { name: 'Из последних сил', description: 'Убить 5 игроков за 5 секунд с 1 хп', category: 'Убийство сталкеров', hidden: true, exp: 10000 },
  { name: 'Из чего это сделано', description: 'Разобрать любой предмет', category: 'Исследование', hidden: false, exp: 400 },
  { name: 'Индивидуальная победа', description: 'Индивидуальная победа в ПВП локации', category: 'Арена', hidden: false, exp: 1000 },
  { name: 'Инженер', description: 'Совершить 1000 попыток создать устройства', category: 'Создание предметов', hidden: true, exp: 50000 },
  { name: 'Истинный Убийца Зловещего Паукана', description: 'Убить Зловещего Паукана 1000 раз', category: 'События', hidden: true, exp: 5000000 },
  { name: 'Истребитель ПК-шников', description: 'Убить ПК-игроков 100 раз', category: 'Убийство сталкеров', hidden: true, exp: 1000 },
  { name: 'Истребитель бесов', description: 'Убить 100000 бесов', category: 'Убийство противников', hidden: true, exp: 300000 },
  { name: 'Истребитель бляков', description: 'Убить 100000 бляков', category: 'Убийство противников', hidden: true, exp: 300000 },
  { name: 'Истребитель бруторов', description: 'Убить 100000 бруторов', category: 'Убийство противников', hidden: true, exp: 200000 },
  { name: 'Истребитель ведунов', description: 'Убить 100000 ведунов', category: 'Убийство противников', hidden: true, exp: 400000 },
  { name: 'Истребитель верлиок', description: 'Убить 100000 верлиок', category: 'Убийство противников', hidden: true, exp: 300000 },
  { name: 'Истребитель домовых', description: 'Убить 100000 домовых и леших', category: 'Убийство противников', hidden: true, exp: 200000 },
  { name: 'Истребитель драугов', description: 'Убить 100000 драугов', category: 'Убийство противников', hidden: true, exp: 1000000 },
  { name: 'Истребитель кабанов', description: 'Убить 100000 кабанов', category: 'Убийство противников', hidden: true, exp: 200000 },
  { name: 'Истребитель крыс', description: 'Убить 100000 крыс', category: 'Убийство противников', hidden: true, exp: 100000 },
  { name: 'Истребитель медведей', description: 'Убить 100000 медведей', category: 'Убийство противников', hidden: true, exp: 600000 },
  { name: 'Истребитель отверженных', description: 'Убить 100000 отверженных', category: 'Убийство противников', hidden: true, exp: 200000 },
  { name: 'Истребитель пауков', description: 'Убить 100000 пауков', category: 'Убийство противников', hidden: true, exp: 300000 },
  { name: 'Истребитель репьев', description: 'Убить 100000 репьев', category: 'Убийство противников', hidden: true, exp: 500000 },
  { name: 'Истребитель собак', description: 'Убить 100000 собак', category: 'Убийство противников', hidden: true, exp: 200000 },
  { name: 'Истребитель студней', description: 'Убить 100000 студней', category: 'Убийство противников', hidden: true, exp: 300000 },
  { name: 'Как семечки', description: 'Убить 50000 игроков на ПвП арене', category: 'Арена', hidden: true, exp: 2000000 },
  { name: 'Караван', description: 'Добро пожаловать на локацию "Караван"', category: 'Исследование', hidden: true, exp: 4000 },
  { name: 'Квартальный отчет', description: 'Успешно выполнить задание "Аномальное родео" 100 раз.', category: 'События', hidden: true, exp: 5000 },
  { name: 'Клининговая компания', description: 'Почистить 1000 единиц оружия', category: 'Ремонт', hidden: true, exp: 30000 },
  { name: 'Книжный червь', description: 'Успешно выполнить задание "Ученье - свет" 100 раз.', category: 'События', hidden: true, exp: 50000 },
  { name: 'Командная победа', description: 'Командная победа в ПВП локации', category: 'Арена', hidden: false, exp: 2000 },
  { name: 'Командный боец', description: 'Вступить в группировку', category: 'Группировка', hidden: false, exp: 1000 },
  { name: 'Конструктор', description: 'Совершить 1000 попыток создать сложные предметы', category: 'Создание предметов', hidden: true, exp: 10000 },
  { name: 'Король снега', description: 'Победить в бою на снежках на Новогодней локации', category: 'События', hidden: true, exp: 1000 },
  { name: 'Кошмар', description: 'Убить 100000 игроков во время захватов', category: 'Захваты', hidden: true, exp: 5000000 },
  { name: 'Кровь и мёд', description: 'Убить 100 эльфов находясь в форме медведя.', category: 'События', hidden: false, exp: 500 },
  { name: 'Крысиная работа', description: 'Умереть от серой крысы', category: 'Смерть', hidden: true, exp: 0 },
  { name: 'Кузнец', description: 'Совершить 1000 попыток создать простые предметы', category: 'Создание предметов', hidden: true, exp: 10000 },
  { name: 'Купец', description: 'Купить на доске 1000 предметов', category: 'Торговля', hidden: true, exp: 40000 },
  { name: 'Куплю АКБ. Дорого.', description: 'Собрать 100 аккумуляторов', category: 'Торговля', hidden: true, exp: 0 },
  { name: 'Куриная сытость', description: 'Скормить курице 10000 единиц хлеба', category: 'Страдания', hidden: true, exp: 50000 },
  { name: 'Лаборант', description: 'Совершить 100 попыток создать химикаты', category: 'Создание предметов', hidden: false, exp: 2000 },
  { name: 'Легенда преступного мира', description: 'Получить ПК-статус 30000 единиц. Тебя разыскивает вся зона!', category: 'Нарушения', hidden: true, exp: 15000 },
  { name: 'Легенда станции', description: 'Успешно выполнить задание "Пикник на обочине" 100 раз.', category: 'События', hidden: true, exp: 25000 },
  { name: 'Лед тронулся', description: 'Завершить событие "Забытые льды"', category: 'События', hidden: false, exp: 10000 },
  { name: 'Ловкие руки', description: 'Зарядить 1000 магазинов патронами', category: 'Зарядка', hidden: false, exp: 1000 },
  { name: 'Любеч без кабанов!', description: 'Убить кабана из Нагана в Любече', category: 'Убийство противников', hidden: true, exp: 200 },
  { name: 'Любеч-1', description: 'Добро пожаловать в "Любеч"', category: 'Исследование', hidden: true, exp: 500 },
  { name: 'Люблю жареное', description: 'Пожарить 1000 единиц еды на костре. Картошка, грибы, мясо: все в огонь.', category: 'Создание предметов', hidden: true, exp: 1000 },
  { name: 'Мам, меня обижают', description: 'Заказать игрока на доске', category: 'Нарушения', hidden: true, exp: 0 },
];

// Все известные категории — используются для легенды и, при необходимости,
// для фильтра по категориям.
export const ACHIEVEMENT_CATEGORIES = [...new Set(ACHIEVEMENTS.map(a => a.category))];
