// Данные достижений Stay Out — ПОЛНЫЙ список (304 шт.), взят со страницы
// so-wiki.ru/wiki/Достижения (сохранённая HTML-копия страницы, распаршена целиком).
// Формат: { name, description, category, hidden, exp }

export const ACHIEVEMENTS = [
  { name: '"Бульдозер"', description: 'Успешно пройти событие "Бульдозер" и получить награду', category: 'События', hidden: false, exp: 2000 },
  { name: '"Другая жизнь Ивана"', description: 'Собрать всю историю "Другая жизнь Ивана"', category: 'Истории', hidden: true, exp: 500000 },
  { name: '"Забытый чемодан"', description: 'Успешно пройти событие "Забытый чемодан" и получить награду', category: 'События', hidden: false, exp: 2000 },
  { name: '"Обелиск"', description: 'Успешно пройти событие "Обелиск" и получить награду', category: 'События', hidden: false, exp: 2000 },
  { name: '"Противогаз и розы"', description: 'Собрать весь сборник стихов "Противогаз и розы"', category: 'Истории', hidden: true, exp: 600000 },
  { name: '"Разбитый колокол"', description: 'Успешно пройти событие "Разбитый колокол" и получить награду', category: 'События', hidden: false, exp: 2000 },
  { name: '"Старый телевизор"', description: 'Успешно пройти событие "Старый телевизор" и получить награду', category: 'События', hidden: false, exp: 2000 },
  { name: '"Юность"', description: 'Собрать всю коллекцию журналов "Юность"', category: 'Истории', hidden: true, exp: 150000 },
  { name: 'Адская кухня', description: 'Убить 100 пряничных человечков во время Пряничного безумия.', category: 'События', hidden: true, exp: 500 },
  { name: 'Аномальная коллекция', description: 'Собрать все виды и типы артефактов с помощью МЗА из аномалий.', category: 'Артефакты', hidden: true, exp: 100000 },
  { name: 'Артефактовый король', description: 'Извлечь из аномалий 1000 артефактов любого типа', category: 'Артефакты', hidden: true, exp: 30000 },
  { name: 'Аэропорт Конуково', description: 'Добро пожаловать на локацию "Аэропорт"', category: 'Исследование', hidden: true, exp: 2000 },
  { name: 'Банчила', description: 'Продать на доске объявлений 1000 предметов', category: 'Торговля', hidden: true, exp: 40000 },
  { name: 'Барыга', description: 'Продать НИПу предметов на сумму 1000000 рублей', category: 'Торговля', hidden: true, exp: 1000 },
  { name: 'Бинтарь, в душе', description: 'Совершить 1000 попыток создать бинты', category: 'Создание предметов', hidden: true, exp: 1000 },
  { name: 'Биохимик', description: 'Совершить 1000 попыток создать пробирки с кровью и ядом мутантов', category: 'Создание предметов', hidden: true, exp: 40000 },
  { name: 'Боевой медик', description: 'Поднять на ноги другого игрока лежащего без сознания 1000 раз', category: 'Лечение', hidden: true, exp: 30000 },
  { name: 'Бунтарь', description: 'Стрелять перед охраной и улететь из безопаски', category: 'Нарушения', hidden: true, exp: 0 },
  { name: 'Быть ПК - нехорошо', description: 'Получить ПК-статус', category: 'Нарушения', hidden: true, exp: 500 },
  { name: 'В законе', description: 'Побывать в Тюрьме 1000 раз. Похоже, тюрьма вам ближе реального мира', category: 'Исследование', hidden: true, exp: 40000 },
  { name: 'В подъездах опасно', description: 'Быть застреленным в подъезде на Окрестностях Любеча', category: 'Убийство сталкеров', hidden: true, exp: 0 },
  { name: 'В списке форбс', description: 'Накопить 100000000 рублей', category: 'Торговля', hidden: true, exp: 100000 },
  { name: 'Вандал', description: 'Разобрать 100 предметов', category: 'Исследование', hidden: true, exp: 1000 },
  { name: 'Везувий', description: 'Добро пожаловать на локацию "Везувий"', category: 'Исследование', hidden: true, exp: 2000 },
  { name: 'Ветеринар', description: 'Совершить 100 попытоксоздать пробирки с кровью и ядом мутантов', category: 'Создание предметов', hidden: false, exp: 4000 },
  { name: 'Вечно второй', description: 'Занять 2 место в любом ивенте 10 раз', category: 'События', hidden: true, exp: 500 },
  { name: 'Внимательный', description: 'Найти спрятанный схрон', category: 'Исследование', hidden: false, exp: 200 },
  { name: 'Воин', description: 'Убить 1000 игроков во время захватов', category: 'Захваты', hidden: true, exp: 50000 },
  { name: 'Вот ты какой 6Б13', description: 'Обменять Метеор на 6Б13', category: 'Торговля', hidden: true, exp: 10000 },
  { name: 'Врач', description: 'Полечить других игроков 1000 раз', category: 'Лечение', hidden: true, exp: 30000 },
  { name: 'Все получится', description: 'Неудача при создании любого предмета', category: 'Создание предметов', hidden: true, exp: 200 },
  { name: 'Всегда первый', description: 'Занять первое место в любом ивенте', category: 'События', hidden: true, exp: 1000 },
  { name: 'Выживший с Радиостанции', description: 'Собрать все записки выжившего с Радиостанции', category: 'Истории', hidden: true, exp: 10000 },
  { name: 'Глубина', description: 'Самая глубокая точка в мире', category: 'Исследование', hidden: false, exp: 5000 },
  { name: 'Голод не тетка', description: 'Съесть сырое мясо', category: 'Выживание', hidden: true, exp: 300 },
  { name: 'Гроза бесов', description: 'Убить 10000 бесов', category: 'Убийство противников', hidden: true, exp: 30000 },
  { name: 'Гроза бляков', description: 'Убить 10000 бляков', category: 'Убийство противников', hidden: true, exp: 30000 },
  { name: 'Гроза бруторов', description: 'Убить 10000 бруторов', category: 'Убийство противников', hidden: true, exp: 20000 },
  { name: 'Гроза ведунов', description: 'Убить 10000 ведунов', category: 'Убийство противников', hidden: true, exp: 40000 },
  { name: 'Гроза верлиок', description: 'Убить 10000 верлиок', category: 'Убийство противников', hidden: true, exp: 30000 },
  { name: 'Гроза домовых', description: 'Убить 10000 домовых или леших', category: 'Убийство противников', hidden: true, exp: 20000 },
  { name: 'Гроза драугов', description: 'Убить 10000 драугов', category: 'Убийство противников', hidden: true, exp: 100000 },
  { name: 'Гроза кабанов', description: 'Убить 10000 кабанов', category: 'Убийство противников', hidden: true, exp: 20000 },
  { name: 'Гроза крыс', description: 'Убить 10000 крыс', category: 'Убийство противников', hidden: true, exp: 10000 },
  { name: 'Гроза медведей', description: 'Убить 10000 медведей', category: 'Убийство противников', hidden: true, exp: 60000 },
  { name: 'Гроза отверженных', description: 'Убить 10000 отверженных', category: 'Убийство противников', hidden: true, exp: 20000 },
  { name: 'Гроза пауков', description: 'Убить 10000 пауков', category: 'Убийство противников', hidden: true, exp: 30000 },
  { name: 'Гроза репьев', description: 'Убить 10000 репьев', category: 'Убийство противников', hidden: true, exp: 50000 },
  { name: 'Гроза собак', description: 'Убить 10000 собак', category: 'Убийство противников', hidden: true, exp: 20000 },
  { name: 'Гроза студней', description: 'Убить 10000 студней', category: 'Убийство противников', hidden: true, exp: 30000 },
  { name: 'Гурман', description: 'Посетить локацию Гурман', category: 'Исследование', hidden: true, exp: 200 },
  { name: 'Да будет свет', description: 'Зажечь спички', category: 'Выживание', hidden: true, exp: 100 },
  { name: 'Да сколько можно', description: 'Быть застреленным игроком 200 раз', category: 'Убийство сталкеров', hidden: true, exp: 2000 },
  { name: 'Делец', description: 'Продать НИПу предметов на сумму 100000 рублей', category: 'Торговля', hidden: true, exp: 100 },
  { name: 'Дипломатия', description: 'Заключить союз с другой группировкой', category: 'Группировка', hidden: false, exp: 500 },
  { name: 'Домашняя работа', description: 'Собрать все материалы по истории о беженцах одного школьного класса', category: 'Истории', hidden: true, exp: 40000 },
  { name: 'Дробилка мне не ровня!', description: 'Продержаться минуту в дробилке и не умереть', category: 'Выживание', hidden: true, exp: 2000 },
  { name: 'За что', description: 'Быть застреленным игроком', category: 'Убийство сталкеров', hidden: true, exp: 0 },
  { name: 'Зажигательный бармен', description: 'Совершить 1000 попыток создать Коктейль Молотова', category: 'Создание предметов', hidden: true, exp: 20000 },
  { name: 'Закупщик', description: 'Купить на доске 100 предметов', category: 'Торговля', hidden: true, exp: 4000 },
  { name: 'Записки потерянного сталкера', description: 'Собрать все записки потерянного сталкера', category: 'Истории', hidden: true, exp: 5000 },
  { name: 'Зато в цирке не выступаю!', description: 'Забраться на Золотой Шар в городе N в форме медведя, и встать на задние лапы.', category: 'Исследование', hidden: true, exp: 500 },
  { name: 'Заядлый Убийца Зловещего Паукана', description: 'Убить Зловещего Паукана 100 раз', category: 'События', hidden: true, exp: 500000 },
  { name: 'Золотые руки', description: 'Починить экипировку с помощью набора для подшива одежды', category: 'Ремонт', hidden: false, exp: 3000 },
  { name: 'Зона забрала', description: 'Умереть от аномалии', category: 'Смерть', hidden: true, exp: 0 },
  { name: 'И шлем не помеха', description: 'Попасть (или убить) выстрелом в голову через шлем с расстояния 200 метров', category: 'Убийство сталкеров', hidden: true, exp: 50000 },
  { name: 'И это ты называешь удар', description: 'Во время события Куча Мала и Мутантов Шабаш, находясь в форме крысы, убить другого игрока, который находится в форме человека.', category: 'События', hidden: true, exp: 500 },
  { name: 'Игра - это моя жизнь', description: 'Провести в игре 5000 часов', category: 'Исследование', hidden: true, exp: 5000000 },
  { name: 'Из последних сил', description: 'Убить 5 игроков за 5 секунд с 1 хп', category: 'Убийство сталкеров', hidden: true, exp: 10000 },
  { name: 'Из чего это сделано', description: 'Разобрать любой предмет', category: 'Исследование', hidden: false, exp: 400 },
  { name: 'Индивидуальная победа', description: 'Индивидуальная победа в ПВП локации', category: 'Арена', hidden: false, exp: 1000 },
  { name: 'Инженер', description: 'Совершить 1000 попыток создать устройства', category: 'Создание предметов', hidden: true, exp: 50000 },
  { name: 'Истинный Убийца Зловещего Паукана', description: 'Убить Зловещего Паукана 1000 раз', category: 'События', hidden: true, exp: 5000000 },
  { name: 'Истребитель ПК-шников', description: 'Убить ПК-игроков 100 раз', category: 'Убийство сталкеров', hidden: true, exp: 1000 },
  { name: 'Истребитель бесов', description: 'Убить 100000 бесов', category: 'Убийство противников', hidden: true, exp: 300000 },
  { name: 'Истребитель бляков', description: 'Убить 100000 бляков', category: 'Убийство противников', hidden: true, exp: 300000 },
  { name: 'Истребитель бруторов', description: 'Убить 100000 бруторов', category: 'Убийство противников', hidden: true, exp: 200000 },
  { name: 'Истребитель ведунов', description: 'Убить 100000 ведунов', category: 'Убийство противников', hidden: true, exp: 400000 },
  { name: 'Истребитель верлиок', description: 'Убить 100000 верлиок', category: 'Убийство противников', hidden: true, exp: 300000 },
  { name: 'Истребитель домовых', description: 'Убить 100000 домовых и леших', category: 'Убийство противников', hidden: true, exp: 200000 },
  { name: 'Истребитель драугов', description: 'Убить 100000 драугов', category: 'Убийство противников', hidden: true, exp: 1000000 },
  { name: 'Истребитель кабанов', description: 'Убить 100000 кабанов', category: 'Убийство противников', hidden: true, exp: 200000 },
  { name: 'Истребитель крыс', description: 'Убить 100000 крыс', category: 'Убийство противников', hidden: true, exp: 100000 },
  { name: 'Истребитель медведей', description: 'Убить 100000 медведей', category: 'Убийство противников', hidden: true, exp: 600000 },
  { name: 'Истребитель отверженных', description: 'Убить 100000 отверженных', category: 'Убийство противников', hidden: true, exp: 200000 },
  { name: 'Истребитель пауков', description: 'Убить 100000 пауков', category: 'Убийство противников', hidden: true, exp: 300000 },
  { name: 'Истребитель репьев', description: 'Убить 100000 репьев', category: 'Убийство противников', hidden: true, exp: 500000 },
  { name: 'Истребитель собак', description: 'Убить 100000 собак', category: 'Убийство противников', hidden: true, exp: 200000 },
  { name: 'Истребитель студней', description: 'Убить 100000 студней', category: 'Убийство противников', hidden: true, exp: 300000 },
  { name: 'Как семечки', description: 'Убить 50000 игроков на ПвП арене', category: 'Арена', hidden: true, exp: 2000000 },
  { name: 'Караван', description: 'Добро пожаловать на локацию "Караван"', category: 'Исследование', hidden: true, exp: 4000 },
  { name: 'Квартальный отчет', description: 'Успешно выполнить задание "Аномальное родео" 100 раз.', category: 'События', hidden: true, exp: 5000 },
  { name: 'Клининговая компания', description: 'Почистить 1000 единиц оружия', category: 'Ремонт', hidden: true, exp: 30000 },
  { name: 'Книжный червь', description: 'Успешно выполнить задание "Ученье - свет" 100 раз.', category: 'События', hidden: true, exp: 50000 },
  { name: 'Командная победа', description: 'Командная победа в ПВП локации', category: 'Арена', hidden: false, exp: 2000 },
  { name: 'Командный боец', description: 'Вступить в группировку', category: 'Группировка', hidden: false, exp: 1000 },
  { name: 'Конструктор', description: 'Совершить 1000 попыток создать сложные предметы', category: 'Создание предметов', hidden: true, exp: 10000 },
  { name: 'Король снега', description: 'Победить в бою на снежках на Новогодней локации', category: 'События', hidden: true, exp: 1000 },
  { name: 'Кошмар', description: 'Убить 100000 игроков во время захватов', category: 'Захваты', hidden: true, exp: 5000000 },
  { name: 'Кровь и мёд', description: 'Убить 100 эльфов находясь в форме медведя.', category: 'События', hidden: false, exp: 500 },
  { name: 'Крысиная работа', description: 'Умереть от серой крысы', category: 'Смерть', hidden: true, exp: 0 },
  { name: 'Кузнец', description: 'Совершить 1000 попыток создать простые предметы', category: 'Создание предметов', hidden: true, exp: 10000 },
  { name: 'Купец', description: 'Купить на доске 1000 предметов', category: 'Торговля', hidden: true, exp: 40000 },
  { name: 'Куплю АКБ. Дорого.', description: 'Собрать 100 аккумуляторов', category: 'Торговля', hidden: true, exp: 0 },
  { name: 'Куриная сытость', description: 'Скормить курице 10000 единиц хлеба', category: 'Страдания', hidden: true, exp: 50000 },
  { name: 'Лаборант', description: 'Совершить 100 попыток создать химикаты', category: 'Создание предметов', hidden: false, exp: 2000 },
  { name: 'Легенда преступного мира', description: 'Получить ПК-статус 30000 единиц. Тебя разыскивает вся зона!', category: 'Нарушения', hidden: true, exp: 15000 },
  { name: 'Легенда станции', description: 'Успешно выполнить задание "Пикник на обочине" 100 раз.', category: 'События', hidden: true, exp: 25000 },
  { name: 'Лед тронулся', description: 'Завершить событие "Забытые льды"', category: 'События', hidden: false, exp: 10000 },
  { name: 'Ловкие руки', description: 'Зарядить 1000 магазинов патронами', category: 'Зарядка', hidden: false, exp: 1000 },
  { name: 'Любеч без кабанов!', description: 'Убить кабана из Нагана в Любече', category: 'Убийство противников', hidden: true, exp: 200 },
  { name: 'Любеч-1', description: 'Добро пожаловать в "Любеч"', category: 'Исследование', hidden: true, exp: 500 },
  { name: 'Люблю жареное', description: 'Пожарить 1000 единиц еды на костре. Картошка, грибы, мясо: все в огонь.', category: 'Создание предметов', hidden: true, exp: 1000 },
  { name: 'Мам, меня обижают', description: 'Заказать игрока на доске', category: 'Нарушения', hidden: true, exp: 0 },
  { name: 'Маньяк', description: 'Убить игроков 10000 раз', category: 'Убийство сталкеров', hidden: true, exp: 100000 },
  { name: 'Марафонец', description: 'Пробежать расстояние 42 км 195 м', category: 'Исследование', hidden: false, exp: 42195 },
  { name: 'Мастер все ломать', description: 'Разобрать 1000 предметов', category: 'Исследование', hidden: true, exp: 5000 },
  { name: 'Мастер заточки', description: 'Заточить 1000 ножей с помощью точильного камня', category: 'Ремонт', hidden: true, exp: 30000 },
  { name: 'Мастер по цеху', description: 'Совершить 1000 попыток создать компоненты электроники', category: 'Создание предметов', hidden: true, exp: 40000 },
  { name: 'Матерый Убийца Зловещего Паукана', description: 'Убить Зловещего Паукана 10 раз', category: 'События', hidden: true, exp: 50000 },
  { name: 'Медбрат', description: 'Вылечите какого-нибудь сталкера. Хорошие дела не проходят зря!', category: 'Лечение', hidden: false, exp: 300 },
  { name: 'Мелкий торговец', description: 'Продать на доске объявлений любой предмет', category: 'Торговля', hidden: false, exp: 400 },
  { name: 'Меняла', description: 'Совершить 100 обменов с НИП', category: 'Торговля', hidden: true, exp: 2000 },
  { name: 'Местный шериф', description: 'Выполнить заказ с доски объявлений 100 раз', category: 'Охота за головами', hidden: true, exp: 5000 },
  { name: 'Меткий бросок', description: 'Убить гранатой 1000 игроков', category: 'Убийство сталкеров', hidden: true, exp: 10000 },
  { name: 'Меткий выстрел', description: 'Совершить самоубийство от гранаты выпущенной из подствольника', category: 'Убийство сталкеров', hidden: true, exp: 0 },
  { name: 'Меткий стрелок', description: 'Убить любую верлиоку в глаз', category: 'Убийство противников', hidden: true, exp: 500 },
  { name: 'Мне нравится ремонтировать', description: 'Ремонт 100 единиц оружия', category: 'Ремонт', hidden: false, exp: 3000 },
  { name: 'Мне повезет', description: 'Съесть ядовитый гриб', category: 'Выживание', hidden: true, exp: 300 },
  { name: 'Мой первый артефакт', description: 'Извлечь из аномалии артефакт любого типа', category: 'Артефакты', hidden: false, exp: 300 },
  { name: 'Мой первый миллион', description: 'Накопить 1000000 рублей', category: 'Торговля', hidden: false, exp: 100 },
  { name: 'Мой первый час', description: 'Провести в игре 1 час', category: 'Исследование', hidden: false, exp: 500 },
  { name: 'Мой первый эпсилон', description: 'Найдите в аномалии артефакт качество не ниже эпсилон', category: 'Артефакты', hidden: false, exp: 1300 },
  { name: 'Мороз не проблема', description: 'Завершить событие "Забытые льды" 10 раз', category: 'События', hidden: true, exp: 50000 },
  { name: 'Морская прогулка', description: 'Прокатиться на любой лодке', category: 'Исследование', hidden: false, exp: 400 },
  { name: 'Моя первая', description: 'Обнаружить свою первую аномалию', category: 'Исследование', hidden: false, exp: 100 },
  { name: 'Моя первая альфа', description: 'Найдите в аномалии артефакт качество не ниже альфа', category: 'Артефакты', hidden: false, exp: 300 },
  { name: 'Моя первая бета', description: 'Найдите в аномалии артефакт качество не ниже бета', category: 'Артефакты', hidden: false, exp: 600 },
  { name: 'Моя первая гамма', description: 'Найдите в аномалии артефакт качество не ниже гамма', category: 'Артефакты', hidden: false, exp: 900 },
  { name: 'Моя первая дельта', description: 'Найдите в аномалии артефакт качество не ниже дельта', category: 'Артефакты', hidden: false, exp: 1100 },
  { name: 'Моя первая заточка', description: 'Заточить нож с помощью точильного камня', category: 'Ремонт', hidden: false, exp: 300 },
  { name: 'Мультикилл', description: 'Хедшот 3 игрокам подряд из снайперской винтовки во время захвата', category: 'Убийство сталкеров', hidden: true, exp: 5000 },
  { name: 'Мы наведем тут порядки!', description: 'Создать свою группировку', category: 'Группировка', hidden: false, exp: 5000 },
  { name: 'Мясник', description: 'Разделать 100000 любых монстров', category: 'Добыча', hidden: true, exp: 200000 },
  { name: 'На вершине мира', description: 'Самая высокая точка мира', category: 'Исследование', hidden: false, exp: 5000 },
  { name: 'На свободу с чистой совестью', description: 'Выйти из тюрьмы', category: 'Исследование', hidden: true, exp: 500 },
  { name: 'Надежное ружьё', description: 'Убить бурого медведя из ТОЗ-34', category: 'Убийство противников', hidden: true, exp: 10000 },
  { name: 'Настоящий охотник ходит с ТОЗ-34', description: 'Убить белого медведя из ТОЗ-34', category: 'Убийство противников', hidden: true, exp: 50000 },
  { name: 'Начинающий повар', description: 'Приготовить одно блюдо в котелке', category: 'Создание предметов', hidden: false, exp: 300 },
  { name: 'Наш путь - война', description: 'Быть в войне с 10 группировками', category: 'Группировка', hidden: true, exp: 50000 },
  { name: 'Наша первая война', description: 'Объявить войну другой группировке', category: 'Группировка', hidden: false, exp: 500 },
  { name: 'Не шуми', description: 'Успешно выполнить задание "Ученье - свет" 10 раз.', category: 'События', hidden: true, exp: 2500 },
  { name: 'Небольшая пробежка', description: 'Пробежать расстояние 1 км', category: 'Исследование', hidden: false, exp: 100 },
  { name: 'Невероятный', description: 'Убить 10000 игроков на ПвП арене', category: 'Арена', hidden: true, exp: 100000 },
  { name: 'Невнимательный покупатель', description: 'Купить на доске протухший артефакт', category: 'Торговля', hidden: true, exp: 0 },
  { name: 'Ненавижу живых', description: 'Добить игрока 1000 раз', category: 'Убийство сталкеров', hidden: true, exp: 10000 },
  { name: 'Новобранец', description: 'Убить 5 игроков во время захватов', category: 'Захваты', hidden: true, exp: 500 },
  { name: 'Ну ты даёшь!', description: 'Браво, вы зарядили 100000 магазин. Врагам не позавидуешь!', category: 'Зарядка', hidden: true, exp: 100000 },
  { name: 'О. Северный', description: 'Добро пожаловать на локацию "Новая Земля о. Северный"', category: 'Исследование', hidden: true, exp: 5000 },
  { name: 'О. Южный', description: 'Добро пожаловать на локацию "Новая Земля о. Южный"', category: 'Исследование', hidden: true, exp: 6000 },
  { name: 'Обезумевший пряник', description: 'Победить в "Пряничном безумии" за пряника', category: 'События', hidden: true, exp: 2000 },
  { name: 'Обмен', description: 'Совершить один обмен с НИП', category: 'Торговля', hidden: false, exp: 200 },
  { name: 'Обыск', description: 'Обыскать любого монстра', category: 'Добыча', hidden: false, exp: 200 },
  { name: 'Оглушающий выстрел', description: 'Убить из подствольного гранатомёта 1000 игроков', category: 'Убийство сталкеров', hidden: true, exp: 20000 },
  { name: 'Одежда должна быть целой', description: 'Починить 100 единиц экипировки с помощью набора для подшива одежды', category: 'Ремонт', hidden: false, exp: 3000 },
  { name: 'Одной жизни мало', description: 'Использовать психомоторный стимулятор', category: 'Выживание', hidden: true, exp: 500 },
  { name: 'Окрестности', description: 'Добро пожаловать на локацию "Окрестности Любеча"', category: 'Исследование', hidden: true, exp: 1000 },
  { name: 'Она движется!', description: 'Обнаружить двигающуюся аномалию', category: 'Исследование', hidden: false, exp: 400 },
  { name: 'Они заряжают пушку! Зачем', description: 'Убить 3 игроков одним попаданием огненного снежка во время командно боя снежками в городе N.', category: 'События', hidden: true, exp: 500 },
  { name: 'Опасные топи', description: 'Завершить событие "Усов-Топи"', category: 'События', hidden: false, exp: 10000 },
  { name: 'Опытный охотник', description: 'Разделать 10000 любых монстров', category: 'Добыча', hidden: true, exp: 20000 },
  { name: 'Опытный шмональщик', description: 'Обыскать 10000 любых монстров', category: 'Добыча', hidden: true, exp: 20000 },
  { name: 'Опять работа', description: 'Успешно выполнить задание "Пикник на обочине" 10 раз.', category: 'События', hidden: true, exp: 250 },
  { name: 'Охотник', description: 'Разделать 1000 любых монстров', category: 'Добыча', hidden: false, exp: 2000 },
  { name: 'Охотник за артефактами', description: 'Извлечь из аномалий 100 артефактов любого типа', category: 'Артефакты', hidden: false, exp: 3000 },
  { name: 'Охотник за головами', description: 'Выполнить заказ с доски объявлений 1000 раз', category: 'Охота за головами', hidden: true, exp: 50000 },
  { name: 'Охотник за грибами', description: 'Завершить событие "Улей" 10 раз', category: 'События', hidden: true, exp: 50000 },
  { name: 'Охотник на бесов', description: 'Убить 1000 бесов', category: 'Убийство противников', hidden: true, exp: 3000 },
  { name: 'Охотник на бляков', description: 'Убить 1000 бляков', category: 'Убийство противников', hidden: true, exp: 3000 },
  { name: 'Охотник на бруторов', description: 'Убить 1000 бруторов', category: 'Убийство противников', hidden: true, exp: 2000 },
  { name: 'Охотник на ведунов', description: 'Убить 1000 ведунов', category: 'Убийство противников', hidden: true, exp: 4000 },
  { name: 'Охотник на верлиок', description: 'Убить 1000 верлиок', category: 'Убийство противников', hidden: true, exp: 3000 },
  { name: 'Охотник на домовых', description: 'Убить 1000 домовых или леших', category: 'Убийство противников', hidden: true, exp: 2000 },
  { name: 'Охотник на драугов', description: 'Убить 1000 драугов', category: 'Убийство противников', hidden: true, exp: 10000 },
  { name: 'Охотник на кабанов', description: 'Убить 1000 кабанов', category: 'Убийство противников', hidden: true, exp: 2000 },
  { name: 'Охотник на крыс', description: 'Убить 1000 крыс', category: 'Убийство противников', hidden: true, exp: 1000 },
  { name: 'Охотник на медведей', description: 'Убить 1000 медведей', category: 'Убийство противников', hidden: true, exp: 6000 },
  { name: 'Охотник на отверженных', description: 'Убить 1000 отверженных', category: 'Убийство противников', hidden: true, exp: 2000 },
  { name: 'Охотник на пауков', description: 'Убить 1000 пауков', category: 'Убийство противников', hidden: true, exp: 3000 },
  { name: 'Охотник на репьев', description: 'Убить 1000 репьев', category: 'Убийство противников', hidden: true, exp: 5000 },
  { name: 'Охотник на собак', description: 'Убить 1000 собак', category: 'Убийство противников', hidden: true, exp: 2000 },
  { name: 'Охотник на студней', description: 'Убить 1000 студней', category: 'Убийство противников', hidden: true, exp: 3000 },
  { name: 'Очистка в промышленных масштабах', description: 'Совершить 1000 попыток очистить воду активированным углем', category: 'Создание предметов', hidden: true, exp: 20000 },
  { name: 'Палач', description: 'Убить 50000 игроков во время захватов', category: 'Захваты', hidden: true, exp: 2000000 },
  { name: 'Панцирь не спасёт', description: 'Убить панцирную верлиоку в глаз', category: 'Убийство противников', hidden: true, exp: 1000 },
  { name: 'Паразиты', description: 'Умереть от паразита', category: 'Смерть', hidden: false, exp: 0 },
  { name: 'Первая сотня', description: 'Убить 100 игроков на ПвП арене', category: 'Арена', hidden: true, exp: 1000 },
  { name: 'Первая ходка', description: 'Побывать в тюрьме в первый раз', category: 'Исследование', hidden: true, exp: 200 },
  { name: 'Победа в соревновании "Капут слизням"', description: 'Победа в соревновании "Капут слизням"', category: 'Соревнования', hidden: false, exp: 5000 },
  { name: 'Победа в соревновании "Лучший охотник"', description: 'Победа в соревновании "Лучший охотник"', category: 'Соревнования', hidden: false, exp: 5000 },
  { name: 'Победа в соревновании "Сбор макулатуры"', description: 'Победа в соревновании "Сбор макулатуры"', category: 'Соревнования', hidden: false, exp: 5000 },
  { name: 'Повар', description: 'Приготовить 100 блюд в котелке', category: 'Создание предметов', hidden: false, exp: 3000 },
  { name: 'Подмастерье', description: 'Совершить 100 попыток создать простые предметы', category: 'Создание предметов', hidden: false, exp: 1000 },
  { name: 'Поднять свой флаг', description: 'Поднять флаг при захвате базы или укрепточки. Гордый морской обычай не позволяет спускать флаг. Никогда!', category: 'Захваты', hidden: false, exp: 500 },
  { name: 'Покупатель', description: 'Купить на доске объявлений любой предмет', category: 'Торговля', hidden: false, exp: 400 },
  { name: 'Полевой санитар', description: 'Поднять на ноги другого игрока лежащего без сознания', category: 'Лечение', hidden: false, exp: 300 },
  { name: 'Помогать моё призвание', description: 'Поднять на ноги другого игрока лежащего без сознания 100 раз', category: 'Лечение', hidden: false, exp: 3000 },
  { name: 'Помощник', description: 'Совершить 100 попыток создать компоненты электроники', category: 'Создание предметов', hidden: false, exp: 4000 },
  { name: 'Портной', description: 'Починить 1000 единиц экипировки с помощью набора для подшива одежды', category: 'Ремонт', hidden: true, exp: 30000 },
  { name: 'Посиделки у костра', description: 'Просидеть у костра и не дать ему потухнуть 1 час. Время реальное.', category: 'Исследование', hidden: true, exp: 50000 },
  { name: 'Потревожил улей', description: 'Завершить событие "Улей"', category: 'События', hidden: false, exp: 10000 },
  { name: 'Почетный грузчик', description: 'Погрузить 1000 ящиков в вездеход в событии "Усов-Топи"', category: 'События', hidden: true, exp: 50000 },
  { name: 'Пробки вышибло', description: 'Успешно выполнить задание "Аномальное родео"', category: 'События', hidden: false, exp: 500 },
  { name: 'Провизор', description: 'Совершить 1000 попыток создать медицинские препараты из старых лекарств', category: 'Создание предметов', hidden: true, exp: 10000 },
  { name: 'Проводник', description: 'Посетить местность "Проводник"', category: 'Исследование', hidden: true, exp: 1000 },
  { name: 'Пройденное посвящение', description: 'Успешно выполнить задание "Оставь надежду всяк сюда входящий"', category: 'События', hidden: false, exp: 500 },
  { name: 'Пропавшие лабораторные крысы', description: 'Собрать историю "Пропавшие лабораторные крысы"', category: 'Истории', hidden: true, exp: 400000 },
  { name: 'Пропала собака!', description: 'Помочь разыскать ту самую собаку', category: 'Истории', hidden: true, exp: 1000 },
  { name: 'Прости, Гриня', description: 'Убить Гриню в подвале города Н', category: 'Убийство противников', hidden: true, exp: 400 },
  { name: 'Просто монстр', description: 'Убить 1000 игроков на ПвП арене', category: 'Арена', hidden: true, exp: 50000 },
  { name: 'Профессор микологии', description: 'Завершить событие "Улей" 100 раз', category: 'События', hidden: true, exp: 500000 },
  { name: 'Пусть все нас знают', description: 'Купить эмблему группировки', category: 'Группировка', hidden: false, exp: 2000 },
  { name: 'Путь дьявола', description: 'Пробежать расстояние 666 км', category: 'Исследование', hidden: true, exp: 666666 },
  { name: 'Радиация убивает', description: 'Умереть от лучевой болезни', category: 'Смерть', hidden: true, exp: 0 },
  { name: 'Разделка', description: 'Разделать любого монстра', category: 'Добыча', hidden: false, exp: 200 },
  { name: 'Разрыватель ПК-шников', description: 'Убить ПК-игроков 10000 раз', category: 'Убийство сталкеров', hidden: true, exp: 100000 },
  { name: 'Район №...10', description: 'Успешно выполнить задание "Аномальное родео" 10 раз.', category: 'События', hidden: true, exp: 2500 },
  { name: 'Ремонт - моя профессия', description: 'Ремонт 1000 единиц оружия', category: 'Ремонт', hidden: true, exp: 30000 },
  { name: 'Ремонтник', description: 'Отремонтировать одно оружие', category: 'Ремонт', hidden: false, exp: 300 },
  { name: 'Рыночные отношения', description: 'Совершить 1000 обменов с НИП', category: 'Торговля', hidden: true, exp: 20000 },
  { name: 'Рядовой', description: 'Убить 100 игроков во время захватов', category: 'Захваты', hidden: true, exp: 5000 },
  { name: 'С ружьем на крупную дичь', description: 'Убить рыжего медведя из ТОЗ-34', category: 'Убийство противников', hidden: true, exp: 25000 },
  { name: 'Самогонщик', description: 'Совершить 1000 попыток создания настойки', category: 'Создание предметов', hidden: true, exp: 30000 },
  { name: 'Сбился со счета', description: 'Убить 100000 игроков на ПвП арене', category: 'Арена', hidden: true, exp: 5000000 },
  { name: 'Сборщик', description: 'Создать 100 сложных предметов', category: 'Создание предметов', hidden: false, exp: 1000 },
  { name: 'Скорострел', description: 'Убить 5 игроков за 5 секунд во время захвата баз или укрепточек', category: 'Захваты', hidden: true, exp: 50000 },
  { name: 'Смерть брассом', description: 'Спасение утопающих - дело рук самих утопающих', category: 'Смерть', hidden: true, exp: 0 },
  { name: 'Смотри под ноги', description: 'Разбиться упав с высоты', category: 'Смерть', hidden: true, exp: 0 },
  { name: 'Снайпер элит', description: 'Попасть (или убить) выстрелом в голову игрока с расстояния 200 метров', category: 'Убийство сталкеров', hidden: true, exp: 40000 },
  { name: 'Собрать артефакт Метеор', description: 'Собрать артефакт Метеор', category: 'Создание предметов', hidden: false, exp: 2500000 },
  { name: 'Спаситель Везувия', description: 'Завершить событие "Улей" 1000 раз', category: 'События', hidden: true, exp: 5000000 },
  { name: 'Спаситель праздника', description: 'Занять первое место в "Пряничном безумии" за человека', category: 'События', hidden: true, exp: 2000 },
  { name: 'Специалист в области дегазации', description: 'Успешно выполнить задание "Оставь надежду всяк сюда входящий" 100 раз.', category: 'События', hidden: true, exp: 50000 },
  { name: 'Старая школа', description: 'Убить из нагана 1000 игроков', category: 'Убийство сталкеров', hidden: true, exp: 10000 },
  { name: 'Стиратель ПК-шников', description: 'Убить ПК-игроков 50000 раз', category: 'Убийство сталкеров', hidden: true, exp: 2000000 },
  { name: 'Странные находки', description: 'Собрать всю коллекцию странных находок', category: 'Истории', hidden: true, exp: 1000 },
  { name: 'Страшная пещера', description: 'Посетить Зловещую "Пещеру Паукана"', category: 'Исследование', hidden: true, exp: 2000 },
  { name: 'Стреляю всех подряд', description: 'Убить 100 союзников или соклановцев во время захвата. Возможно, вам стоит пересмотреть жизненные цели, раз вы так расправляетесь с друзьями', category: 'Захваты', hidden: true, exp: 0 },
  { name: 'Стреляю с закрытыми глазами', description: 'Убить союзника или соклановца во время захвата баз или укрепточек', category: 'Захваты', hidden: true, exp: 0 },
  { name: 'Сыщик', description: 'Обыскать 100000 любых монстров', category: 'Добыча', hidden: true, exp: 200000 },
  { name: 'Тайных ход', description: 'Тайный проход в Любеч', category: 'Исследование', hidden: true, exp: 200 },
  { name: 'Так всем спокойнее', description: 'Добить игрока 100 раз', category: 'Убийство сталкеров', hidden: true, exp: 1000 },
  { name: 'Так спокойнее', description: 'Добить игрока 1 раз', category: 'Убийство сталкеров', hidden: true, exp: 100 },
  { name: 'Так теплее', description: 'Сжечь 6Б13', category: 'Страдания', hidden: true, exp: 2500000 },
  { name: 'Теперь дорога безопасна', description: 'Завершить событие "Усов-Топи" 1000 раз', category: 'События', hidden: true, exp: 5000000 },
  { name: 'Теперь я видел всё', description: 'Обнаружить все виды аномалий', category: 'Исследование', hidden: false, exp: 8000 },
  { name: 'Техник', description: 'Совершить 100 попыток создать устройства', category: 'Создание предметов', hidden: false, exp: 5000 },
  { name: 'Тихий убийца', description: 'Убить игрока из оружия с глушителем', category: 'Убийство сталкеров', hidden: true, exp: 400 },
  { name: 'Только не по левой', description: 'Завершить событие "Усов-Топи" 10 раз', category: 'События', hidden: true, exp: 50000 },
  { name: 'Топим дальше', description: 'Завершить событие "Усов-Топи" 100 раз', category: 'События', hidden: true, exp: 500000 },
  { name: 'Торгаш', description: 'Продать на доске объявлений 100 предметов', category: 'Торговля', hidden: true, exp: 4000 },
  { name: 'Точильщик', description: 'Заточить 100 ножей с помощью точильного камня', category: 'Ремонт', hidden: false, exp: 3000 },
  { name: 'Травник', description: 'Совершить 100 попыток создать настойки', category: 'Создание предметов', hidden: false, exp: 3000 },
  { name: 'Три товарища', description: 'Успешно выполнить задание "Пикник на обочине" 1000 раз.', category: 'События', hidden: true, exp: 250000 },
  { name: 'Трубочист', description: 'Успешно выполнить задание "Оставь надежду всяк сюда входящий" 10 раз.', category: 'События', hidden: true, exp: 2500 },
  { name: 'Тунгуска', description: 'Добро пожаловать на локацию "Тунгуска"', category: 'Исследование', hidden: true, exp: 4000 },
  { name: 'Тяжесть в животе', description: 'Умереть от пищевого отравления', category: 'Смерть', hidden: true, exp: 0 },
  { name: 'Убивать - мой выбор', description: 'Убить игроков 1000 раз', category: 'Убийство сталкеров', hidden: true, exp: 5000 },
  { name: 'Убивать - моё призвание', description: 'Получить ПК-статус 10000 единиц. Как будем отмываться?', category: 'Нарушения', hidden: true, exp: 5000 },
  { name: 'Убийца', description: 'Убить 10000 игроков во время захватов', category: 'Захваты', hidden: true, exp: 500000 },
  { name: 'Убийца Зловещего Паукана', description: 'Убить Зловещего Паукана', category: 'События', hidden: false, exp: 5000 },
  { name: 'Убийца Ледяного Паукана', description: 'Убить Ледяного Паукана', category: 'События', hidden: true, exp: 5000 },
  { name: 'Удержание базы!', description: 'Успешно удержать базу или укрепточку. Аватар на момент захвата должен быть онлайн, в радиусе базы и состоять в победившем клане.', category: 'Захваты', hidden: false, exp: 5000 },
  { name: 'Умение выживать', description: 'Успеть убить 3 мобов при 1% здоровья', category: 'Убийство противников', hidden: true, exp: 5000 },
  { name: 'Уничтожитель ПК-шников', description: 'Убить ПК-игроков 1000 раз', category: 'Убийство сталкеров', hidden: true, exp: 10000 },
  { name: 'Уничтожитель Хранителя Вулкана', description: 'Убить Хранителя Вулкана', category: 'События', hidden: false, exp: 5000 },
  { name: 'Успешная доставка', description: 'Успешно выполнить задание "Пикник на обочине"', category: 'События', hidden: false, exp: 100 },
  { name: 'Успешный захват!', description: 'Успешный захват базы или укрепточки. Аватар на момент захвата должен быть онлайн, в радиусе базы и состоять в победившем клане.', category: 'Захваты', hidden: false, exp: 5000 },
  { name: 'Ученье - свет', description: 'Успешно выполнить задание "Ученье - свет" 1000 раз.', category: 'События', hidden: true, exp: 500000 },
  { name: 'Фармацевт', description: 'Создать 100 медицинских препаратов из старых лекарств', category: 'Создание предметов', hidden: false, exp: 1000 },
  { name: 'Фельдшер', description: 'Полечить других игроков 100 раз', category: 'Лечение', hidden: false, exp: 3000 },
  { name: 'Финансовый воротила', description: 'Продать НИПу предметов на сумму 50000000 рублей', category: 'Торговля', hidden: true, exp: 50000 },
  { name: 'Хедшот', description: 'Хедшот из СВД на расстоянии более 120 метров', category: 'Убийство сталкеров', hidden: true, exp: 10000 },
  { name: 'Химик', description: 'Совершить 1000 попыток создать химикаты', category: 'Создание предметов', hidden: true, exp: 20000 },
  { name: 'Холодное сердце', description: 'Завершить событие "Забытые льды" 100 раз', category: 'События', hidden: true, exp: 500000 },
  { name: 'Художник', description: 'Раскрасить любую вещь', category: 'Исследование', hidden: true, exp: 1000 },
  { name: 'Царь зимы', description: 'Завершить событие "Забытые льды" 1000 раз', category: 'События', hidden: true, exp: 5000000 },
  { name: 'Черный лес', description: 'Добро пожаловать на локацию "Черный лес"', category: 'Исследование', hidden: true, exp: 12000 },
  { name: 'Четвертый разряд', description: 'Успешно выполнить задание "Аномальное родео" 1000 раз.', category: 'События', hidden: true, exp: 500000 },
  { name: 'Чистильщик', description: 'Почистить одно оружие', category: 'Ремонт', hidden: false, exp: 300 },
  { name: 'Читательский билет', description: 'Успешно выполнить задание "Ученье - свет"', category: 'События', hidden: false, exp: 500 },
  { name: 'Что в ваших карманах', description: 'Обыскать 1000 любых монстров', category: 'Добыча', hidden: false, exp: 2000 },
  { name: 'Что я наделал', description: 'Совершить первое убийство игрока', category: 'Убийство сталкеров', hidden: true, exp: 200 },
  { name: 'Чтоб блестело', description: 'Почистить 100 единиц оружия', category: 'Ремонт', hidden: false, exp: 3000 },
  { name: 'Чужая месть', description: 'Выполнить заказ с доски объявлений', category: 'Охота за головами', hidden: false, exp: 500 },
  { name: 'Шеф-повар', description: 'Приготовить 1000 блюд в котелке', category: 'Создание предметов', hidden: false, exp: 30000 },
  { name: 'Эпичное самоубийство', description: 'Самоубийство от гранаты', category: 'Убийство сталкеров', hidden: true, exp: 0 },
  { name: 'Эх, прокачу!', description: 'Прокатиться хоть раз с Колей Баранка', category: 'Исследование', hidden: false, exp: 400 },
  { name: 'Юбилейная ходка', description: 'Побывать в Тюрьме 100 раз. Мы думаем, что вы уже умеете писать письма при помощи молока и хлеба.', category: 'Исследование', hidden: true, exp: 4000 },
  { name: 'Я защищался', description: 'Поздравляем, у вас 100 убийств', category: 'Убийство сталкеров', hidden: true, exp: 1000 },
  { name: 'Я крыса, и горжусь этим!', description: 'Во время события Куча Мала и Мутантов Шабаш, находясь в форме крысы, убить другого игрока, который также находится в форме крысы.', category: 'События', hidden: true, exp: 500 },
  { name: 'Я монстр', description: 'Побывать в шкуре любого монстра', category: 'Исследование', hidden: true, exp: 0 },
  { name: 'Я просто мясо', description: 'Быть застреленным игроком 1000 раз', category: 'Убийство сталкеров', hidden: true, exp: 0 },
  { name: 'Я пью только чистую воду', description: 'Совершить 100 попыток очистить воду активированным углем', category: 'Создание предметов', hidden: true, exp: 2000 },
];

// Все известные категории — используются для легенды/фильтра.
export const ACHIEVEMENT_CATEGORIES = [...new Set(ACHIEVEMENTS.map(a => a.category))];